### ISSUE TITLE
Nothing Happened Prompt when using Jet Antidote v20

### ISSUE THREAD

**Issue by siveon** [BGforgeNet/Fallout2_Unofficial_Patch#78] opened 2021-06-06 03:07 UTC
### What happened
Nothing happened when using Jet Antidote. Aquired Jet Antidote after finding out infomation on development from Myron. Also spoke to Myron about creating a cure himself beforehand. Completed handing the doctor in Vault City jet, and also spoke with the Counselman about the Redding issue with Jet. Loading different saves at any point with Jet Antidote hacked in does not cure the Jet addiction. 
### What you expected to happen
Cure for Jet Addiction, removal of reliance and debuffs. 
### Screenshot
![image](https://user-images.githubusercontent.com/36186313/120911082-4f995980-c652-11eb-95ac-4bcd6c687f05.png)

### Savegame
[SLOT47.zip](https://github.com/BGforgeNet/Fallout2_Unofficial_Patch/files/6603565/SLOT47.zip)

**Comment by burner1024** [comment] 2021-06-06 03:23
this save crashes on load

**Comment by siveon** [comment] 2021-06-06 04:02
Forgot to mention, includes mods party orders and inventory filter and hero appearance.

**Comment by burner1024** [comment] 2021-06-06 04:11
nvm, I thought it was RPU. I can confirm the issue.

**Comment by burner1024** [comment] 2021-06-06 04:14
Do you have a pre-addiction save with some jet to test?

**Comment by siveon** [comment] 2021-06-06 04:18
Yeah I have one 4 in-game days before addiction. It has jet on the character. 
[SLOT04.zip](https://github.com/BGforgeNet/Fallout2_Unofficial_Patch/files/6603619/SLOT04.zip)

**Comment by burner1024** [comment] 2021-06-06 04:41
Antidote works in the second save. So it looks like the first one got corrupted somehow.

**Comment by siveon** [comment] 2021-06-06 04:49
Any way to fix this, or at least remove the addict prompt manually?

**Comment by burner1024** [comment] 2021-06-06 05:10
I suspect that you're not actually addicted, but some data didn't clear properly, which is why antidote does nothing.
Try popping a few more jets, then use the antidote.

**Comment by siveon** [comment] 2021-06-06 05:14
Oh, huh, that worked. 
Only in Fallout could I say, "I just needed to take more drugs to be cured."
I will mention I got addicted with one Jet usage, but it's a 50/50 chance so that's not surprising.

**Comment by burner1024** [comment] 2021-06-06 05:21
OK, if you see this again, or better yet, find a way to reproduce the glitch, feel free to add that info. Without that, it's hardly possible to find the cause, so closing for now.

**Closed by burner1024** 2021-06-06 05:21 UTC
